#!/usr/bin/env bash

DEFAULTS[0]="txt|leafpad"
DEFAULTS[1]="pdf|mupdf"
DEFAULTS[2]="png,jpg,jpeg|gpicview"
DEFAULTS[3]="mp3|audacious"
DEFAULTS[4]="mp4,avi,wmv,mkv,flv|gnome-mplayer"
DEFAULTS[5]="c,h,cpp,md|urxvt -tn xterm -e vim"
#DEFAULTS[6]="tar,tar.gz,tar.xz,tar.bz2,tgz,txz,tbz2,tz2|urxvt -tn xterm -e mc"

APPLICATIONS_DIR=/usr/share/applications


if [ -e $HOME/.config/kxdg.cfg ]; then
	. $HOME/.config/kxdg.cfg
fi

cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/dmenu_run
else
	cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
fi


GetApplicationFiles()
{
	ext="${1}"
	ffs=$(grep "MimeType=.*${ext}.*" ${APPLICATIONS_DIR}/* | awk -F ':' '{print $1}')
	echo $ffs
	return $(echo -n "$ffs" | wc -l)
}

GetApplicationDefaults()
{
	ext="${1}"
	OLDIFS="$IFS"
	for x in "${DEFAULTS[@]}"; do
		cmd=$(echo "$x" | awk -F '|' '{printf $2}')
		exts=$(echo "$x" | awk -F '|' '{printf $1}')
		aExt=()
		IFS=","
		aExt=($exts)
		IFS="$OLDIFS"
		for y in "${aExt[@]}"; do
			if echo "${ext}" | grep -q -x "${y}"; then
				echo "${cmd}"
				return 0
			fi
		done
	done
	return 1
}

WriteDefaults()
{
	i=0
	:> $HOME/.config/kxdg.cfg
	for x in "${DEFAULTS[@]}"; do
		echo "DEFAULTS[$i]=\"${DEFAULTS[$i]}\"" >> $HOME/.config/kxdg.cfg
		i=$(($i + 1))
	done
}

AddCmd()
{
	i=${#DEFAULTS[@]}
	DEFAULTS[$i]="$1|$2"
}

GetCmd()
{
	cmd=$(
    IFS=:
    if stest -dqr -n "$cache" $PATH; then
        stest -flx $PATH | sort -u | tee "$cache" | dmenu "$@"
    else
        dmenu -p "Choose command to open files $extension" "$@" < "$cache"
    fi)
	echo "$cmd"
}

GetApplicationFile()
{
	cafile=$(dmenu_run -p "Choose from the existing application or type a new command for $1 files")
	echo "$cafile"
}

RunCMD()
{
	full=$(readlink -f "$2")
	if [ -n "$(echo "$1" | grep "%[fF]")" ]; then
		cmd=$(echo "$1" | sed -e "s|%[fF]|$full|g")
		${cmd} &
	elif [ -n "$(echo "$1" | grep "%[uU]")" ]; then
		cmd=$(echo "$1" | sed -e "s|%[U]|file://$full|g")
		${cmd} &
	else
		${1} "${2}" &
	fi
}

extension="${1/*./}"
aFiles=$(GetApplicationFiles $extension)
iFiles=$?
cmd=$(GetApplicationDefaults $extension)
if [ -z "$cmd" ]; then
	if [ $iFiles -eq 1 ]; then
		cmd=$(grep "Exec=.*%.*" "${aFiles}")
	elif [ $iFiles -eq 0 ]; then
		cmd=$(GetCmd)
	else
		for x in ${aFiles[@]}; do
			name=$(grep "^Name=.*" "${x}" | awk -F '=' '{print $2}')
			names="$names $name"
		done
		afile=$(GetApplicationFile)
		cmd=$(grep "Exec=.*%.*" "${afile}")
	fi
	if [ -n "$cmd" ]; then
		AddCmd "${extension}" "${cmd}"
		WriteDefaults
	fi
fi
RunCMD ${cmd} "${1}"
exit 0

